Added *Harvest tables support; corrected help screen

diff --git a/iphone_tools/iphone_cs b/iphone_tools/iphone_cs
--- a/iphone_tools/iphone_cs
+++ b/iphone_tools/iphone_cs
@@ -1,12 +1,12 @@
 #!/bin/bash
 #: Title 	: iphone_cs
 #: Author	: "John Lehr" <slo.sleuth@gmail.com>
-#: Date		: 07/25/2011
-#: Version	: 1.0.2
+#: Date		: 08/10/2011
+#: Version	: 1.0.3
 #: Description	: Dump/interpret iphone consolidated.db messages table 
 #: Options	: None
 
-#: 07/25/2011 : v1.0.3 
+#: 08/10/2011 : v1.0.3 added WifiLocationHarvest support
 #: 05/04/2011 : v1.0.2 added dependency checking
 #: 04/12/2011 : v1.0.1 mapping support added for gpsvisualizer.com
 #: 04/11/2011 : v1.0.0 Initial Release
@@ -30,7 +30,7 @@ map=0
 
 usage()
 {
-	echo "USAGE: $progname [-chlmw] file"
+	echo "USAGE: $progname [-cChHlLmrwWV] file"
 	echo "       where 'file' is an iPhone consolidated.db"
 	cat << EOF
 	
@@ -38,17 +38,20 @@ Options (only one table option may be used at a time):
 
 	Table options:
 	-C	Parse CellLocation table
+	-CH	Parse CellLocationHarvest table
 	-L	Parse CellLocationLocal table
 	-W 	Parse WifiLocation table
+	-WH	Parse WifiLocationHarvest table
 	
 	Formatting options:
 	-c	output to csv (default is sqlite list format)
-	-H	output to html
+	-w	output to html (web)
 	-l	output each one field per line
 	-m	mapping format (csv)
 	-r	raw (dump the full table, no conversion)
 
 	Other:
+	-h 	this help
 	-V	carrier is Verizon (CDMA)
 
 Options MUST preceed the database to be processed. 
@@ -65,12 +68,12 @@ celllocation()
 {
 	## export CellLocation table to stdout
 	if [ $map = 1 ]; then
-		sqlite3 -header -csv $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'name', Latitude, Longitude from ${verizon}CellLocation WHERE Latitude != 0.0"
+		sqlite3 -header -csv $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'name', Latitude, Longitude from ${verizon}CellLocation${harvest} WHERE Latitude != 0.0"
 		notice
 	elif [ $raw = 1 ]; then
-		sqlite3 -header $format $db "SELECT * FROM ${verizon}CellLocation"
+		sqlite3 -header $format $db "SELECT * FROM ${verizon}CellLocation${harvest}"
 	else
-		sqlite3 -header $format $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'Time Stamp', Latitude, Longitude from ${verizon}CellLocation"
+		sqlite3 -header $format $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'Time Stamp', Latitude, Longitude from ${verizon}CellLocation${harvest}"
 	fi
 }
 
@@ -78,12 +81,12 @@ celllocationlocal()
 {
 	## export CellLocationLocal table to stdout
 	if [ $map = 1 ]; then
-		sqlite3 -header -csv $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'name', 'Speed: ' || round(Speed, 1) || ' at ' || round(Course, 1) || ' Degrees' as Desc, Latitude, Longitude from ${verizon}CellLocationLocal"
+		sqlite3 -header -csv $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'name', 'Speed: ' || round(Speed, 1) || ' at ' || round(Course, 1) || ' Degrees' as Desc, Latitude, Longitude from ${verizon}CellLocationLocal${harvest}"
 		notice
 	elif [ $raw = 1 ]; then
-		sqlite3 -header $format $db "SELECT * FROM ${verizon}CellLocationLocal"
+		sqlite3 -header $format $db "SELECT * FROM ${verizon}CellLocationLocal${harvest}"
 	else
-		sqlite3 -header $format $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'Time Stamp', Latitude, Longitude, rtrim(round(Speed),'.0') as Speed, rtrim(round(Course),'.0') as Direction from ${verizon}CellLocationLocal"
+		sqlite3 -header $format $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'Time Stamp', Latitude, Longitude, rtrim(round(Speed),'.0') as Speed, rtrim(round(Course),'.0') as Direction from ${verizon}CellLocationLocal${harvest}"
 	fi
 }
 
@@ -106,23 +109,12 @@ wifilocation()
 {
 	## export WifiLocation table to stdout
 	if [ $map = 1 ]; then
-		sqlite3 -header -csv $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'Name', 'MAC Address: ' || MAC as Desc, Latitude, Longitude from WifiLocation where Latitude != 0.0"
+		sqlite3 -header -csv $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'Name', 'MAC Address: ' || MAC as Desc, Latitude, Longitude from WifiLocation${harvest} where Latitude != 0.0"
 		notice
 	elif [ $raw = 1 ]; then
-		sqlite3 -header $format $db "SELECT * FROM WifiLocation"
+		sqlite3 -header $format $db "SELECT * FROM WifiLocation${harvest}"
 	else
-		sqlite3 -header $format $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'Time Stamp', Latitude, Longitude, MAC from WifiLocation"
-	fi
-}
-
-wifilocationharvest()
-{
-	## export WifiLocation table to stdout
-	if [ $map = 1 ]; then
-		sqlite3 -header -csv $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'Name', 'MAC Address: ' || MAC as Desc, Latitude, Longitude from WifiLocationHarvest"
-		notice
-	else
-		sqlite3 -header $format $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'Time Stamp', Latitude, Longitude, MAC from WifiLocationHarvest"
+		sqlite3 -header $format $db "SELECT datetime(Timestamp + 978307200, 'unixepoch', 'localtime') AS 'Time Stamp', Latitude, Longitude, MAC from WifiLocation${harvest}"
 	fi
 }
 
@@ -138,13 +130,14 @@ while getopts $optstring opt; do
 		c) csv=1; format=-csv ;;
 		C) cell=1 ;;
 		h) usage >&2; exit 0 ;;
-		H) html=1; format=-html ;;
+		H) harvest=Harvest ;;
 		l) line=1; format=-line ;;
 		L) local=1 ;;
 		m) map=1 ;;
 		r) raw=1 ;;
+		w) html=1; format=-html ;;
 		W) wifi=1 ;;
-		V) verizon=CDMA ;;
+		V) verizon=Cdma ;;
 		*) echo; usage >&2; exit 1 ;;
 	esac
 done
@@ -170,7 +163,7 @@ elif [ $(($cell+$local+$wifi)) -lt 1 ]; then
 fi
 
 if [ $(($csv+$html+$line)) -gt 1 ]; then
-	echo "Error: arguments -c -H -l and -L may not be used together" >&2
+	echo "Error: formatting arguments -c -w and -l may not be used together" >&2
 	exit 1
 fi
 
@@ -180,7 +173,7 @@ if [ $cell = 1 ]; then
 	celllocation
 elif [ $local = 1 ]; then
 	celllocationlocal
-else
+elif [ $wifi = 1 ]; then
 	wifilocation
 fi
 
