bug fixes to fmount, improvements to mounter.

diff --git a/miscellaneous/fmount b/miscellaneous/fmount
--- a/miscellaneous/fmount
+++ b/miscellaneous/fmount
@@ -61,11 +61,15 @@ mount_volumes()
     if [ $? -eq 0 ] && [ $MOUNTER -eq 1 ] 
     then
         tskfuse.py -o ro,allow_other,offset=$(($OFFSET*512)) "$IMAGE" "$MNTPNT"
+        [ $? -gt 0 ] && echo "Mounting error." && exit 1
         TOOL=\"tskfuse.py\"
     else
-        [[ "$(fsstat -o $OFFSET $IMAGE | head -3)" =~ NTFS ]] && NTFS_OPTS=",show_sys_files,streams_interface=windows"
-        mount -o ro,loop,offset=$(($OFFSET*512)),user$NTFS_OPTS "$IMAGE" "$MNTPNT"
-        TOOL=\"mount\"
+        [[ "$(fsstat -o $OFFSET $IMAGE | head -3)" =~ NTFS ]] && \
+            NTFS_OPTS=,show_sys_files,streams_interface=windows,allow_other && \
+            FSTYPE=-t\ ntfs-3g
+        mount $FSTYPE -o ro,loop,offset=$(($OFFSET*512)),user$NTFS_OPTS "$IMAGE" "$MNTPNT"
+        [ $? -gt 0 ] && echo "Mounting error." && exit 1
+        TOOL="\"mount\" command"
     fi
 }
 
@@ -150,11 +154,11 @@ else
                 do
                     OFFSET=${OFFSET#0}
                 done
-    
+
                 MNTPNT="/media/$DIR_NAME/${DIR_NAME}_vol$VOLUME/"
                 mkdir -p "$MNTPNT"
                 echo "${LINE[5]} file system detected in volume $VOLUME at sector offset $OFFSET" >&2
-    
+
                 mount_volumes
                 echo -e "\tmounted at $MNTPNT with $TOOL" >&2
             fi
diff --git a/miscellaneous/mounter b/miscellaneous/mounter
--- a/miscellaneous/mounter
+++ b/miscellaneous/mounter
@@ -1,20 +1,29 @@
 #!/bin/bash
 #: Title    : mounter
 #: Author   : "John Lehr" <slo.sleuth@gmail.com>
-#: Date     : 09/14/2011
-#: Version  : 0.1.0
-#: Desc     : rewrite fstab on hotplug for write protection
+#: Date     : 09/26/2011
+#: Version  : 0.1.1
+#: Desc     : mount device(s) selected by user
 #: Options  : none
+
+#: 09/26/2011 : added partition size, rbfstab status, mount location/status
+#: 09/14/2011 : Initial release
 
 mount_disks()
 {
     dev_list=
     selection=
     count=0
-    instructions="Detected <b>block devices</b> and their current mount status.
-Unmounted devices will be mounted and vice versa.
+    
+    if [ -e /etc/udev/rules.d/fstab.rules ]
+    then
+        ro="<span size='x-large'>Selected devices will be mounted <b><u>READ-ONLY</u></b>.</span>"
+    else 
+        ro="<span size='x-large'>Selected devices will be mounted <span foreground='red'><b><u>WRITEABLE</u></b></span>.</span>"
+    fi
 
-Select devices to mount/unmount:"
+    instructions="Detected <b>block devices</b> and their current mount status. Unmounted devices will be mounted and vice versa. \n\n$ro \n\nSelect devices to mount/unmount:"
+
     devices=$(blkid -o device | grep -v ram)
 
     for device in $devices
@@ -22,20 +31,34 @@ Select devices to mount/unmount:"
         count=$(($count+1))
         # Determine file system type
         fs_type=$(blkid -s TYPE -o value $device)
-        
+
         # Ignore swap
         [ "$fs_type" = "swap" ] && continue
-        
+
         # Determine volume label
         vol_label=$(blkid -s LABEL -o value $device)
-        [ -z "$vol_label" ] && vol_label="(None)"
-        
+        [ -z "$vol_label" ] && vol_label="(none)"
+
+        # Determine volume size
+        vol_size=$(($(sfdisk -s $device)/1024))
+        vol_size=$(printf "%'d\n" $vol_size)
+
         # Determine if currently mounted
-        grep -q ^$device /etc/mtab
-        [ $? = 0 ] && mounted=Yes || mounted=No
-        
+        mounted=($(grep ^$device /etc/mtab))
+        if [ -z $mounted ] 
+        then 
+            mounted="(none)"
+            status="(none)"
+        else
+            mounted="${mounted[1]}"
+            case ${mounted[3]} in
+                ro*) status="READ-ONLY" ;;
+                rw*) status="Writeable" ;;
+            esac
+        fi
+
         # Create a device list
-        dev_list="$dev_list $count $device ${fs_type// /_} ${vol_label// /_} $mounted"
+        dev_list="$dev_list $count $device ${fs_type// /_} ${vol_label// /_} $vol_size $mounted $status"
     done
     
     selection=$(yad --list \
@@ -45,11 +68,14 @@ Select devices to mount/unmount:"
         --text="$instructions" \
         --column= \
         --column=Device \
-        --column=FS\ Type \
+        --column="FS Type" \
         --column=Label \
-        --column=Mounted \
+        --column="Size (MB)" \
+        --column="Mount Point" \
+        --column=Status \
         --checklist \
-        --height=250 \
+        --height=300 \
+        --width=550 \
         --print-column=2 \
         --button=gtk-refresh:2 \
         --button=gtk-cancel:1 \
@@ -82,10 +108,28 @@ Select devices to mount/unmount:"
         do
             device=${device//|/}
             grep -q ^$device /etc/mtab
-            [ $? = 0 ] && sudo umount $device || sudo mount $device
+            if [ $? = 0 ]
+            then 
+                sudo umount $device 
+                [ $? = 1 ] && yad \
+                    --window-icon=gtk-harddisk \
+                    --image=gtk-dialog-error \
+                    --text="Error: device is busy.  Ensure no applications\nor windows are accessing device and try again."
+            else
+                sudo mount $device
+            fi
         done
     fi
 }
+
+# Test for dependencies:
+deps="yad blkid sfdisk rbfstab"
+for dep in yad blkid rbfstab
+do
+    which $dep >/dev/null
+    [ $? -gt 0 ] && missing=1
+done
+[[ -n $missing ]] && echo -e "Error: missing dependency\nCheck that \"$deps\" are installed"
 
 # Make mount_disks function executable by yad
 export -f mount_disks
