Bug fixes.

diff --git a/miscellaneous/fmount b/miscellaneous/fmount
--- a/miscellaneous/fmount
+++ b/miscellaneous/fmount
@@ -36,6 +36,9 @@ get_image_type()
         *ewf) ITYPE=ewf ;;
         *aff) ITYPE=aff ;;
     esac
+    
+    [ -z $IMG_TYPE ] && echo "Error: unknown image type" && exit 1
+    
     export ITYPE
 }
 
@@ -57,6 +60,7 @@ mount_split_image()
 
 mount_volumes()
 {
+    NTFS_OPTS=
     which tskfuse.py >/dev/null
     if [ $? -eq 0 ] && [ $MOUNTER -eq 1 ] 
     then
